#' Set up UK Biobank metadata for search, extraction, and decoding
#'
#' @description
#' Builds a lightweight metadata object from any combination of RAP-approved
#' fields, a UK Biobank data dictionary, and coding/encoding tables. This is the
#' recommended first step before searching fields, inspecting field definitions,
#' extracting phenotype columns, or decoding RAP exports.
#'
#' @param source Metadata source strategy. `"auto"` uses any supplied files and
#'   tries RAP field discovery when available. `"files"` uses only supplied
#'   files and cached field listings. `"rap"` requires RAP field discovery.
#' @param data_dict Optional UKB data dictionary file, such as a RAP
#'   `data_dictionary.csv` generated by `dx extract_dataset -ddd`, an older
#'   `Data_Dictionary_Showcase.tsv`, or an equivalent tabular export.
#' @param codings Optional UKB coding/encoding table, such as an older
#'   `Codings.tsv` or an equivalent table with coding ID, value, and meaning
#'   columns.
#' @param fields_df Optional cached output from `rap_list_fields()`.
#' @param dataset Optional RAP `.dataset` file name.
#' @param entity RAP dataset entity. Defaults to `"participant"`.
#' @param cache Logical. If `TRUE`, save the metadata object as an RDS file.
#' @param cache_dir Optional cache directory. Defaults to
#'   `tools::R_user_dir("UKBAnalytica", "cache")`.
#' @param refresh Logical. Passed to `rap_list_fields()` when RAP discovery is
#'   used.
#' @param quiet Logical. If `FALSE`, print short messages about unavailable
#'   optional metadata sources.
#'
#' @return An object of class `ukb_metadata`.
#' @export
#'
ukb_metadata_setup <- function(source = c("auto", "files", "rap"),
                               data_dict = NULL,
                               codings = NULL,
                               fields_df = NULL,
                               dataset = NULL,
                               entity = "participant",
                               cache = FALSE,
                               cache_dir = NULL,
                               refresh = FALSE,
                               quiet = FALSE) {
  source <- match.arg(source)
  .ukb_check_scalar_logical(cache, "cache")
  .ukb_check_scalar_logical(refresh, "refresh")
  .ukb_check_scalar_logical(quiet, "quiet")

  if (is.null(cache_dir)) {
    cache_dir <- tools::R_user_dir("UKBAnalytica", which = "cache")
  }

  rap_error <- NULL
  should_try_rap <- source == "rap" ||
    (!identical(source, "files") && (is.null(fields_df) && (!is.null(dataset) || nzchar(Sys.which("dx")))))

  if (is.null(fields_df) && should_try_rap) {
    rap_attempt <- tryCatch(
      list(
        fields_df = rap_list_fields(dataset = dataset, entity = entity, refresh = refresh),
        error = NULL
      ),
      error = function(e) {
        list(fields_df = NULL, error = conditionMessage(e))
      }
    )
    fields_df <- rap_attempt$fields_df
    rap_error <- rap_attempt$error
  }

  if (source == "rap" && is.null(fields_df)) {
    stop("Could not retrieve RAP field metadata: ", rap_error, call. = FALSE)
  }

  fields <- NULL
  if (!is.null(data_dict) || !is.null(fields_df)) {
    fields <- get_field_metadata(
      ukb_data_dict = data_dict,
      fields_df = fields_df,
      dataset = NULL,
      entity = entity
    )
  } else {
    fields <- .field_metadata_empty()
    if (!isTRUE(quiet)) {
      message(
        "[ukb_metadata_setup] No data dictionary or RAP field list was available. ",
        "Field search will be empty until metadata is supplied."
      )
    }
  }

  fields <- .ukb_metadata_normalize_fields(fields)
  rap_fields <- if (!is.null(fields_df)) .ukb_parse_rap_fields(fields_df, entity = entity) else .ukb_empty_rap_fields()
  coding_tbl <- if (!is.null(codings)) .ukb_read_codings(codings) else .ukb_empty_codings()

  out <- list(
    fields = fields,
    rap_fields = rap_fields,
    codings = coding_tbl,
    categories = data.frame(stringsAsFactors = FALSE),
    source = list(
      mode = source,
      data_dict = data_dict,
      codings = codings,
      dataset = dataset,
      entity = entity,
      built_at = Sys.time(),
      cache_dir = cache_dir,
      rap_error = rap_error
    )
  )
  class(out) <- c("ukb_metadata", "list")

  if (isTRUE(cache)) {
    dir.create(cache_dir, recursive = TRUE, showWarnings = FALSE)
    saveRDS(out, file = file.path(cache_dir, "ukb_metadata.rds"))
  }

  out
}

#' Search UK Biobank fields
#'
#' @param query Optional keyword matched against field title, description,
#'   category, coding ID, and RAP column names.
#' @param field_id Optional UKB field IDs for exact lookup.
#' @param metadata Optional object from `ukb_metadata_setup()`.
#' @param max_results Maximum number of rows to return.
#' @param search_in Columns to search.
#' @param ... Arguments passed to `ukb_metadata_setup()` when `metadata` is
#'   `NULL`.
#'
#' @return A data.frame of class `ukb_search_result`.
#' @export
ukb_search_fields <- function(query = NULL,
                              field_id = NULL,
                              metadata = NULL,
                              max_results = 50,
                              search_in = c("title", "description", "category", "field_name", "rap_field_names", "coding_id"),
                              ...) {
  metadata <- .ukb_require_metadata(metadata, ...)
  fields <- metadata$fields

  if (nrow(fields) == 0) {
    out <- fields
    out$score <- numeric(0)
    out$matched_on <- character(0)
    class(out) <- c("ukb_search_result", class(out))
    attr(out, "query") <- query
    return(out)
  }

  if (!is.null(field_id)) {
    ids <- .field_metadata_normalize_ids(field_id)
    fields <- fields[fields$field_id %in% ids, , drop = FALSE]
  }

  if (!is.null(query)) {
    if (!is.character(query) || length(query) == 0 || anyNA(query)) {
      stop("`query` must be a non-empty character vector.", call. = FALSE)
    }
    query <- trimws(query[nzchar(query)])
    scored <- .ukb_score_field_rows(fields, query = query, search_in = search_in)
    fields <- scored$fields[scored$score > 0, , drop = FALSE]
    fields$score <- scored$score[scored$score > 0]
    fields$matched_on <- scored$matched_on[scored$score > 0]
    fields <- fields[order(-fields$score, fields$field_id), , drop = FALSE]
  } else {
    fields$score <- if (nrow(fields) > 0) 1 else numeric(0)
    fields$matched_on <- if (nrow(fields) > 0) "field_id" else character(0)
    fields <- fields[order(fields$field_id), , drop = FALSE]
  }

  if (!is.null(max_results) && nrow(fields) > max_results) {
    fields <- fields[seq_len(max_results), , drop = FALSE]
  }

  rownames(fields) <- NULL
  class(fields) <- c("ukb_search_result", class(fields))
  attr(fields, "query") <- query
  fields
}

#' Inspect one UK Biobank field
#'
#' @param x A UKB field ID, RAP column name, predefined UKBAnalytica variable
#'   name, or field title keyword.
#' @param by Lookup mode. `"auto"` detects field IDs, RAP columns, predefined
#'   variable names, and otherwise falls back to title search.
#' @param metadata Optional object from `ukb_metadata_setup()`.
#' @param live Logical. If `TRUE` and a single field ID is available, missing
#'   official metadata can be filled from the public UKB Showcase field page.
#' @param ... Arguments passed to `ukb_metadata_setup()` when `metadata` is
#'   `NULL`.
#'
#' @return An object of class `ukb_field_info`.
#' @export
ukb_field_info <- function(x,
                           by = c("auto", "field_id", "title", "rap_column", "variable"),
                           metadata = NULL,
                           live = FALSE,
                           ...) {
  by <- match.arg(by)
  .ukb_check_scalar_logical(live, "live")
  metadata <- .ukb_require_metadata(metadata, ...)

  resolved <- .ukb_resolve_field_input(x, by = by, metadata = metadata)
  if (length(resolved$field_id) == 0) {
    stop("No UKB field matched `x`.", call. = FALSE)
  }

  field <- metadata$fields[metadata$fields$field_id %in% resolved$field_id, , drop = FALSE]

  if (nrow(field) == 0 && isTRUE(live) && length(resolved$field_id) == 1L) {
    field <- get_field_info(resolved$field_id[[1]], live = TRUE)
  } else if (isTRUE(live) && nrow(field) == 1L) {
    live_field <- get_field_info(field$field_id[[1]], live = TRUE)
    field <- .field_metadata_overlay_one(field, live_field)
  }

  rap_fields <- metadata$rap_fields[metadata$rap_fields$field_id %in% resolved$field_id, , drop = FALSE]
  coding_ids <- unique(stats::na.omit(as.character(field$coding_id)))
  coding_ids <- coding_ids[nzchar(coding_ids)]
  codings <- metadata$codings[metadata$codings$coding_id %in% coding_ids, , drop = FALSE]

  out <- list(
    field = field,
    rap_fields = rap_fields,
    codings = codings,
    matched_by = resolved$matched_by,
    query = x,
    summary = .ukb_field_summary(field, rap_fields, codings)
  )
  class(out) <- c("ukb_field_info", "list")
  out
}

#' Extract UK Biobank fields from a search result or field list
#'
#' @param x Optional object returned by `ukb_search_fields()` or
#'   `ukb_field_info()`.
#' @param field_id Optional UKB field IDs. Ignored when `x` supplies IDs.
#' @param metadata Optional object from `ukb_metadata_setup()`.
#' @param mode `"plan"` returns a RAP extraction plan, `"sync"` calls
#'   `rap_extract_pheno()`, and `"job"` calls `rap_submit_extract()`.
#' @param top_n Optional number of top search-result fields to extract.
#' @param dataset Optional RAP `.dataset` file name.
#' @param entity RAP entity. Defaults to `"participant"`.
#' @param ... Additional arguments passed to the selected RAP extraction
#'   function.
#'
#' @return A RAP extraction plan, a data.table, an output path, or a RAP job
#'   submission result depending on `mode`.
#' @export
ukb_extract_fields <- function(x = NULL,
                               field_id = NULL,
                               metadata = NULL,
                               mode = c("plan", "sync", "job"),
                               top_n = NULL,
                               dataset = NULL,
                               entity = "participant",
                               ...) {
  mode <- match.arg(mode)
  metadata <- .ukb_require_metadata(metadata)
  ids <- .ukb_extract_field_ids_from_input(x = x, field_id = field_id, top_n = top_n)
  if (length(ids) == 0) {
    stop("No field IDs were supplied for extraction.", call. = FALSE)
  }

  if (is.null(dataset)) {
    dataset <- metadata$source$dataset
  }
  fields_df <- .ukb_fields_df_from_metadata(metadata)

  if (identical(mode, "plan")) {
    return(rap_plan_extract(field_id = ids, dataset = dataset, fields_df = fields_df, entity = entity, ...))
  }
  if (identical(mode, "sync")) {
    return(rap_extract_pheno(field_id = ids, dataset = dataset, fields_df = fields_df, entity = entity, ...))
  }
  rap_submit_extract(field_id = ids, dataset = dataset, fields_df = fields_df, entity = entity, ...)
}

#' Decode UK Biobank RAP exports
#'
#' @param data A data.frame or data.table.
#' @param metadata Optional object from `ukb_metadata_setup()`.
#' @param decode_names Logical. If `TRUE`, rename UKB columns using field
#'   titles.
#' @param decode_values Logical. If `TRUE`, decode coded values where coding
#'   metadata are available.
#' @param keep_raw Logical. If `TRUE`, decoded labels are added as new columns.
#' @param suffix Suffix for decoded label columns when `keep_raw = TRUE`.
#' @param ... Arguments passed to `ukb_metadata_setup()` when `metadata` is
#'   `NULL`.
#'
#' @return A data.frame or data.table matching the input class.
#' @export
ukb_decode <- function(data,
                       metadata = NULL,
                       decode_names = TRUE,
                       decode_values = TRUE,
                       keep_raw = TRUE,
                       suffix = "_label",
                       ...) {
  metadata <- .ukb_require_metadata(metadata, ...)
  out <- data
  if (isTRUE(decode_values)) {
    out <- ukb_decode_values(out, metadata = metadata, keep_raw = keep_raw, suffix = suffix)
  }
  if (isTRUE(decode_names)) {
    out <- ukb_decode_column_names(out, metadata = metadata)
  }
  out
}

#' Decode UK Biobank coded values
#'
#' @param data A data.frame or data.table.
#' @param metadata Optional object from `ukb_metadata_setup()`.
#' @param keep_raw Logical. If `TRUE`, add label columns and keep raw columns.
#' @param suffix Suffix for label columns when `keep_raw = TRUE`.
#' @param missing_to_na Logical. If `TRUE`, UKB-style negative codes are set to
#'   `NA` in decoded label columns when no explicit label is available.
#' @param ... Arguments passed to `ukb_metadata_setup()` when `metadata` is
#'   `NULL`.
#'
#' @return A data.frame or data.table matching the input class.
#' @export
ukb_decode_values <- function(data,
                              metadata = NULL,
                              keep_raw = TRUE,
                              suffix = "_label",
                              missing_to_na = TRUE,
                              ...) {
  if (!is.data.frame(data)) {
    stop("`data` must be a data.frame or data.table.", call. = FALSE)
  }
  .ukb_check_scalar_logical(keep_raw, "keep_raw")
  .ukb_check_scalar_logical(missing_to_na, "missing_to_na")
  metadata <- .ukb_require_metadata(metadata, ...)

  if (nrow(metadata$codings) == 0 || nrow(metadata$fields) == 0) {
    return(data)
  }

  out <- if (data.table::is.data.table(data)) data.table::copy(data) else data
  parsed <- .ukb_parse_columns(names(out))

  for (i in seq_len(nrow(parsed))) {
    field_id <- parsed$field_id[[i]]
    if (is.na(field_id)) {
      next
    }
    field <- metadata$fields[metadata$fields$field_id == field_id, , drop = FALSE]
    if (nrow(field) == 0 || !"coding_id" %in% names(field)) {
      next
    }
    coding_id <- unique(stats::na.omit(as.character(field$coding_id)))
    coding_id <- coding_id[nzchar(coding_id)]
    if (length(coding_id) == 0) {
      next
    }
    map <- metadata$codings[metadata$codings$coding_id %in% coding_id, , drop = FALSE]
    if (nrow(map) == 0) {
      next
    }

    col <- parsed$column[[i]]
    decoded <- .ukb_decode_vector(out[[col]], map = map, missing_to_na = missing_to_na)
    if (isTRUE(keep_raw)) {
      out[[paste0(col, suffix)]] <- decoded
    } else {
      out[[col]] <- decoded
    }
  }

  out
}

#' Decode UK Biobank column names
#'
#' @param data A data.frame or data.table.
#' @param metadata Optional object from `ukb_metadata_setup()`.
#' @param style Name style. `"snake"` converts field titles to snake_case,
#'   `"title"` uses the official title, and `"field_id_title"` prefixes the
#'   field ID.
#' @param keep_instance Logical. Keep UKB instance suffixes such as `_i0`.
#' @param keep_array Logical. Keep UKB array suffixes such as `_a0`.
#' @param max_nchar Optional maximum column-name length.
#' @param ... Arguments passed to `ukb_metadata_setup()` when `metadata` is
#'   `NULL`.
#'
#' @return A data.frame or data.table matching the input class.
#' @export
ukb_decode_column_names <- function(data,
                                    metadata = NULL,
                                    style = c("snake", "title", "field_id_title"),
                                    keep_instance = TRUE,
                                    keep_array = TRUE,
                                    max_nchar = 80,
                                    ...) {
  if (!is.data.frame(data)) {
    stop("`data` must be a data.frame or data.table.", call. = FALSE)
  }
  style <- match.arg(style)
  .ukb_check_scalar_logical(keep_instance, "keep_instance")
  .ukb_check_scalar_logical(keep_array, "keep_array")
  metadata <- .ukb_require_metadata(metadata, ...)

  parsed <- .ukb_parse_columns(names(data))
  new_names <- names(data)

  for (i in seq_len(nrow(parsed))) {
    field_id <- parsed$field_id[[i]]
    if (is.na(field_id)) {
      next
    }
    field <- metadata$fields[metadata$fields$field_id == field_id, , drop = FALSE]
    if (nrow(field) == 0 || is.na(field$title[[1]]) || !nzchar(field$title[[1]])) {
      next
    }
    base <- switch(
      style,
      snake = .ukb_make_snake_name(field$title[[1]]),
      title = field$title[[1]],
      field_id_title = paste0("p", field_id, "_", .ukb_make_snake_name(field$title[[1]]))
    )
    suffix <- character(0)
    if (isTRUE(keep_instance) && !is.na(parsed$instance[[i]])) {
      suffix <- c(suffix, paste0("i", parsed$instance[[i]]))
    }
    if (isTRUE(keep_array) && !is.na(parsed$array[[i]])) {
      suffix <- c(suffix, paste0("a", parsed$array[[i]]))
    }
    if (nzchar(parsed$extra_suffix[[i]])) {
      suffix <- c(suffix, sub("^_", "", parsed$extra_suffix[[i]]))
    }
    candidate <- paste(c(base, suffix), collapse = "_")
    if (!is.null(max_nchar) && nchar(candidate) > max_nchar) {
      candidate <- substr(candidate, 1L, max_nchar)
    }
    new_names[[i]] <- candidate
  }

  new_names <- make.unique(new_names, sep = "_")
  out <- if (data.table::is.data.table(data)) data.table::copy(data) else data
  names(out) <- new_names
  out
}

#' @export
print.ukb_metadata <- function(x, ...) {
  cat("UKB metadata\n")
  cat(sprintf("  fields: %d\n", nrow(x$fields)))
  cat(sprintf("  RAP columns: %d\n", nrow(x$rap_fields)))
  cat(sprintf("  coding values: %d\n", nrow(x$codings)))
  cat(sprintf("  built_at: %s\n", format(x$source$built_at)))
  invisible(x)
}

#' @export
print.ukb_field_info <- function(x, ...) {
  cat(paste(x$summary, collapse = "\n"), "\n", sep = "")
  invisible(x)
}

.ukb_require_metadata <- function(metadata = NULL, ...) {
  if (is.null(metadata)) {
    metadata <- ukb_metadata_setup(...)
  }
  if (!inherits(metadata, "ukb_metadata")) {
    stop("`metadata` must be an object returned by ukb_metadata_setup().", call. = FALSE)
  }
  metadata
}

.ukb_check_scalar_logical <- function(x, name) {
  if (!isTRUE(x) && !identical(x, FALSE)) {
    stop(sprintf("`%s` must be TRUE or FALSE.", name), call. = FALSE)
  }
}

.ukb_metadata_normalize_fields <- function(fields) {
  if (is.null(fields) || nrow(fields) == 0) {
    fields <- .field_metadata_empty()
  }
  if (!"coding_id" %in% names(fields)) {
    fields$coding_id <- fields$coding
  }
  fields$coding_id <- .ukb_clean_coding_id(fields$coding_id)
  fields
}

.ukb_clean_coding_id <- function(x) {
  x <- as.character(x)
  x[is.na(x)] <- NA_character_
  x <- trimws(x)
  x[!nzchar(x)] <- NA_character_
  x <- sub("^coding[: ]*", "", x, ignore.case = TRUE)
  x
}

.ukb_empty_rap_fields <- function() {
  data.frame(
    entity = character(0),
    field_id = integer(0),
    instance = integer(0),
    array = integer(0),
    rap_column = character(0),
    field_name = character(0),
    title = character(0),
    title_clean = character(0),
    stringsAsFactors = FALSE
  )
}

.ukb_parse_rap_fields <- function(fields_df,
                                  entity = "participant") {
  .rap_assert_fields_df(fields_df)
  parsed <- .ukb_parse_columns(fields_df$field_name, default_entity = entity)
  keep <- !is.na(parsed$field_id)
  if (!any(keep)) {
    return(.ukb_empty_rap_fields())
  }
  out <- data.frame(
    entity = parsed$entity[keep],
    field_id = parsed$field_id[keep],
    instance = parsed$instance[keep],
    array = parsed$array[keep],
    rap_column = fields_df$field_name[keep],
    field_name = fields_df$field_name[keep],
    title = as.character(fields_df$title[keep]),
    title_clean = trimws(sub("\\s*\\|.*$", "", as.character(fields_df$title[keep]))),
    stringsAsFactors = FALSE
  )
  rownames(out) <- NULL
  out
}

.ukb_parse_columns <- function(columns,
                               default_entity = "participant") {
  columns <- as.character(columns)
  re <- "^(([^.]+)\\.)?p([0-9]+)(?:_i([0-9]+))?(?:_a([0-9]+))?((?:_.+)?)$"
  m <- regexec(re, columns, perl = TRUE)
  parts <- regmatches(columns, m)
  out <- data.frame(
    column = columns,
    entity = rep(default_entity, length(columns)),
    field_id = rep(NA_integer_, length(columns)),
    instance = rep(NA_integer_, length(columns)),
    array = rep(NA_integer_, length(columns)),
    extra_suffix = rep("", length(columns)),
    stringsAsFactors = FALSE
  )
  for (i in seq_along(parts)) {
    p <- parts[[i]]
    if (length(p) == 0) {
      next
    }
    out$entity[[i]] <- if (length(p) >= 3L && nzchar(p[[3]])) p[[3]] else default_entity
    out$field_id[[i]] <- suppressWarnings(as.integer(p[[4]]))
    out$instance[[i]] <- suppressWarnings(as.integer(if (length(p) >= 5L && nzchar(p[[5]])) p[[5]] else NA_character_))
    out$array[[i]] <- suppressWarnings(as.integer(if (length(p) >= 6L && nzchar(p[[6]])) p[[6]] else NA_character_))
    out$extra_suffix[[i]] <- if (length(p) >= 7L && nzchar(p[[7]])) p[[7]] else ""
  }
  out
}

.ukb_empty_codings <- function() {
  data.frame(
    coding_id = character(0),
    value = character(0),
    meaning = character(0),
    parent_value = character(0),
    selectable = character(0),
    source = character(0),
    stringsAsFactors = FALSE
  )
}

.ukb_read_codings <- function(path) {
  if (!file.exists(path)) {
    stop("`codings` does not exist: ", path, call. = FALSE)
  }
  raw <- data.table::fread(path, data.table = FALSE, encoding = "UTF-8")
  if (!is.data.frame(raw) || nrow(raw) == 0) {
    stop("`codings` could not be parsed into a non-empty table.", call. = FALSE)
  }

  coding_col <- .field_metadata_pick_col(raw, c("Coding", "Coding ID", "coding_id", "encoding_id", "Encoding"))
  value_col <- .field_metadata_pick_col(raw, c("Value", "Code", "value", "code"))
  meaning_col <- .field_metadata_pick_col(raw, c("Meaning", "Label", "meaning", "label", "Description"))
  parent_col <- .field_metadata_pick_col(raw, c("Parent", "Parent Value", "parent_value"))
  selectable_col <- .field_metadata_pick_col(raw, c("Selectable", "selectable"))

  if (is.null(coding_col) || is.null(value_col) || is.null(meaning_col)) {
    stop(
      "`codings` must include columns equivalent to coding ID, value/code, and meaning/label.",
      call. = FALSE
    )
  }

  out <- data.frame(
    coding_id = .ukb_clean_coding_id(raw[[coding_col]]),
    value = as.character(raw[[value_col]]),
    meaning = as.character(raw[[meaning_col]]),
    parent_value = if (!is.null(parent_col)) as.character(raw[[parent_col]]) else NA_character_,
    selectable = if (!is.null(selectable_col)) as.character(raw[[selectable_col]]) else NA_character_,
    source = basename(path),
    stringsAsFactors = FALSE
  )
  out <- out[!is.na(out$coding_id) & nzchar(out$coding_id) & !is.na(out$value), , drop = FALSE]
  rownames(out) <- NULL
  out
}

.ukb_score_field_rows <- function(fields,
                                  query,
                                  search_in) {
  search_in <- intersect(search_in, names(fields))
  score <- numeric(nrow(fields))
  matched_on <- rep("", nrow(fields))
  if (length(search_in) == 0) {
    return(list(fields = fields, score = score, matched_on = matched_on))
  }

  for (i in seq_len(nrow(fields))) {
    hits <- character(0)
    row_score <- 0
    for (col in search_in) {
      val <- fields[[col]][[i]]
      if (is.na(val) || !nzchar(as.character(val))) {
        next
      }
      val_chr <- tolower(as.character(val))
      for (q in tolower(query)) {
        if (identical(val_chr, q)) {
          row_score <- row_score + 100
          hits <- c(hits, col)
        } else if (grepl(q, val_chr, fixed = TRUE)) {
          row_score <- row_score + if (col == "title") 50 else 20
          hits <- c(hits, col)
        }
      }
    }
    score[[i]] <- row_score
    matched_on[[i]] <- paste(unique(hits), collapse = ";")
  }
  list(fields = fields, score = score, matched_on = matched_on)
}

.ukb_resolve_field_input <- function(x,
                                     by,
                                     metadata) {
  x_chr <- as.character(x)
  x_chr <- trimws(x_chr[nzchar(x_chr)])
  if (length(x_chr) == 0 || anyNA(x_chr)) {
    stop("`x` must contain a non-empty field ID, field title, RAP column, or variable name.", call. = FALSE)
  }

  if (by == "auto") {
    if (all(grepl("^[0-9]+$", x_chr))) {
      by <- "field_id"
    } else if (any(grepl("(^|\\.)p[0-9]+", x_chr))) {
      by <- "rap_column"
    } else {
      vars <- tryCatch(get_variable_info(), error = function(e) NULL)
      if (!is.null(vars) && any(x_chr %in% vars$variable)) {
        by <- "variable"
      } else {
        by <- "title"
      }
    }
  }

  ids <- integer(0)
  if (by == "field_id") {
    ids <- .field_metadata_normalize_ids(x_chr)
  } else if (by == "rap_column") {
    parsed <- .ukb_parse_columns(x_chr)
    ids <- unique(parsed$field_id[!is.na(parsed$field_id)])
  } else if (by == "variable") {
    vars <- get_variable_info()
    hit <- vars[vars$variable %in% x_chr, , drop = FALSE]
    ids <- unique(hit$field_id)
  } else {
    res <- ukb_search_fields(query = x_chr, metadata = metadata, max_results = 10)
    ids <- unique(res$field_id)
  }

  list(field_id = ids, matched_by = by)
}

.ukb_field_summary <- function(field,
                               rap_fields,
                               codings) {
  if (nrow(field) == 0) {
    return("No UKB field metadata found.")
  }
  f <- field[1, , drop = FALSE]
  lines <- c(
    sprintf("UKB field %s", f$field_id[[1]]),
    sprintf("Title: %s", .ukb_value_or_na(f$title[[1]])),
    sprintf("Category: %s", .ukb_value_or_na(f$category[[1]])),
    sprintf("Value type: %s", .ukb_value_or_na(f$value_type[[1]])),
    sprintf("Units: %s", .ukb_value_or_na(f$units[[1]])),
    sprintf("Coding: %s", .ukb_value_or_na(f$coding_id[[1]])),
    sprintf("Instances: %s", .ukb_value_or_na(f$instances[[1]])),
    sprintf("Array: %s", .ukb_value_or_na(f$array[[1]])),
    sprintf("RAP columns: %d", nrow(rap_fields)),
    sprintf("Coding labels: %d", nrow(codings)),
    sprintf("Source: %s", .ukb_value_or_na(f$source_backend[[1]]))
  )
  if ("link" %in% names(f) && !is.na(f$link[[1]]) && nzchar(f$link[[1]])) {
    lines <- c(lines, sprintf("Showcase: %s", f$link[[1]]))
  }
  lines
}

.ukb_value_or_na <- function(x) {
  if (length(x) == 0 || is.na(x) || !nzchar(as.character(x))) {
    return("NA")
  }
  as.character(x)
}

.ukb_extract_field_ids_from_input <- function(x,
                                              field_id,
                                              top_n) {
  if (!is.null(x)) {
    if (inherits(x, "ukb_field_info")) {
      ids <- x$field$field_id
    } else if (is.data.frame(x) && "field_id" %in% names(x)) {
      y <- x
      if (!is.null(top_n)) {
        y <- y[seq_len(min(nrow(y), top_n)), , drop = FALSE]
      }
      ids <- y$field_id
    } else {
      stop("`x` must be a ukb_search_result, ukb_field_info, or data.frame with `field_id`.", call. = FALSE)
    }
  } else {
    ids <- field_id
  }
  as.integer(.field_metadata_normalize_ids(ids))
}

.ukb_fields_df_from_metadata <- function(metadata) {
  if (nrow(metadata$rap_fields) == 0) {
    return(NULL)
  }
  data.frame(
    field_name = metadata$rap_fields$rap_column,
    title = metadata$rap_fields$title,
    stringsAsFactors = FALSE
  )
}

.ukb_decode_vector <- function(x,
                               map,
                               missing_to_na) {
  key <- as.character(x)
  value_key <- as.character(map$value)
  decoded <- map$meaning[match(key, value_key)]
  if (isTRUE(missing_to_na)) {
    neg <- suppressWarnings(as.numeric(key) < 0)
    decoded[is.na(decoded) & !is.na(neg) & neg] <- NA_character_
  }
  decoded
}

.ukb_make_snake_name <- function(x) {
  x <- iconv(as.character(x), to = "ASCII//TRANSLIT")
  x <- tolower(x)
  x <- gsub("[^a-z0-9]+", "_", x)
  x <- gsub("^_+|_+$", "", x)
  if (!nzchar(x)) {
    x <- "ukb_field"
  }
  x
}
