name: quarto-docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: quarto-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr", "remotes"))'
          Rscript -e 'remotes::install_deps(dependencies = c("Depends", "Imports"), upgrade = "never")'
          R CMD INSTALL .

      - name: Render Quarto website
        run: |
          quarto render quarto-site

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
